### ISSUE TITLE
Add changelog or release notes

### ISSUE THREAD

**Issue by hisabimbola** [revdotcom/revai-node-sdk#137]
Hello,

We're using this library for our RevAI integration and seeing that some updates are being made but there is no public documentation to understand what breaking changes or new features are being added. Is it possible to add the support for this?

Thansk

**Comment by amikofalvy** [comment]
There is public documentation for the Node SDK changelog

https://docs.rev.ai/sdk/node/changelog/

**Comment by amikofalvy** [comment]
I will add a link to this changelog in the readme to increase visibility.

**Comment by hisabimbola** [comment]
Thanks for the fast response @amikofalvy. 

1. Looking at the linked changelog, I can't see the breaking change for v3.0.0 I can't only see fixes and new feature. Can you double check that this is correct or maybe there is a breaking change that is not documented?
2. In addition to the website, is it possible to add the changelog to the repo. There are industry standard dependency management tools that parses opensource libraries and extracts the changelog when proposing an update. For [renovate](https://github.com/renovatebot/renovate) this is missing because it's not on the repo.

**Comment by amikofalvy** [comment]
I recall the discussion around bumping the major version of the package. It was introduced in this PR/commit: https://github.com/revdotcom/revai-node-sdk/pull/76#discussion_r791065689

In short, we made a breaking change to the streaming client which is not independently versioned from the asynchronous client so we felt obligated to increase the major version.

If you are using one of the async clients then there should not be a breaking change for your use case.

**Comment by amikofalvy** [comment]
Separately, the engineering team can look into using the GitHub release notes feature. In the past we have not used that functionality. Instead preferring our own change log because of its flexibility.

I cannot promise a timeline for when the team would be be able to look in to this. You are always welcome to submit a PR if you would like to see a change that benefits the community altogether.
