### ISSUE TITLE
Discrepancy between `JobStatus` and valid job status values?

### ISSUE THREAD

**Issue by srubin** [revdotcom/revai-node-sdk#31]
The `JobStatus.Failed` enum is defined as `'failed'`, but the documentation for "Get Job by Id" says that it should be be `'failure'`. https://www.rev.ai/docs#operation/GetJobById

**Comment by kbridbur** [comment]
Hey srubin. I think there's some confusion here. If you look closely at the documentation, the `status` field of a failed job is `failed`. I think what you're referring to is the `failure` and `failure_details` fields. These two fields are captured in the [`RevAiApiJob`](https://github.com/revdotcom/revai-node-sdk/blob/develop/src/models/RevAiApiJob.ts#L15) class of the SDK
<img width="491" alt="Screen Shot 2019-10-24 at 10 29 44 AM" src="https://user-images.githubusercontent.com/18108791/67510100-342e3600-f649-11e9-92fc-3b9fbbcbd876.png">

**Comment by srubin** [comment]
I'm referring to this in the documentation (maybe the documentation for the REST endpoint is wrong?):

![image](https://user-images.githubusercontent.com/433928/67510725-7c5a5200-f663-11e9-9bd7-3f7c607a5e94.png)

**Comment by kbridbur** [comment]
That is definitely a discrepancy. The correct value is `failed`. I'm going to close this ticket and file an issue for our API to fix that documentation. Thanks for pointing this out!
