### ISSUE TITLE
Unable to resolve module fs from F:\Works\Projects\AutoDoc-Dash\node_modules\revai-node-sdk\sr

### ISSUE THREAD

**Issue by Sankarshana-Ananth** [revdotcom/revai-node-sdk#63]
We are trying this service for the first time, and we have ran into this issue.

**Comment by amikofalvy** [comment]
@ShankStack were you able to resolve your issue? Without further details it is difficult to say for certain, but the title of the issue including "F:\Works..." makes me believe that this is an issue with your local file system being unable to resolve the fs node module.

I'll close the issue for now. Please reopen if you think this requires further investigation.

**Comment by SainMar** [comment]
@Sankarshana-Achar or @amikofalvy Did either of you solve the issue? I have the same issue using Next js and the rev.ai-node package

**Comment by amikofalvy** [comment]
@SainMar I can help you investigate if you provide me with additional details. Please include a log trace if possible. If you do not want to share publicly, you can send this information to support@rev.ai
