### ISSUE TITLE
File size limited to 10mb

### ISSUE THREAD

**Issue by oscarlgz** [revdotcom/revai-node-sdk#72]
This project uses `axios`, which limits the body size to 10mb by default (via `maxBodyLength`). See https://axios-http.com/docs/req_config.

This limit should probably be increased to 2gb to match the API, or at least be configurable. Currently the `submitJobLocalFile` will throw an error if files larger than 10mb

**Comment by amikofalvy** [comment]
Thanks for creating this issue. The team will look into it, in the meantime, feel free contribute a fix as a PR.

**Comment by amikofalvy** [comment]
We recommend that you use a media_url to submit large files to the API. Multipart upload has limited support and should only be used if no other options are available.

**Comment by amikofalvy** [comment]
https://github.com/revdotcom/revai-node-sdk/pull/74
