### ISSUE TITLE
Support language in SessionConfig

### ISSUE THREAD

**Issue by chishun-mosaicvoice** [revdotcom/revai-node-sdk#90]
Hi, you recently released foreign language support https://rev-ai-non-english-streaming.redoc.ly/#section/WebSocket-Endpoint/Language-(Labs), but `SessionConfig` still does not take a language, seems like a pretty straight forward addition.

Thanks!

**Comment by amikofalvy** [comment]
Hello, @chishun-mosaicvoice.

The requested feature is currently in a Closed Beta. Our official SDKs may not support features operating in closed beta.
